message("Working!")

base = github.branch_for_base
merging = github.branch_for_head

message("This pr merge #{merging} into #{base}")

if base == "main" || base == "master"
    unless merging.start_with?("hotfix/") || merging.start_with?("release/")
        fail("You can't merge this branch into main/master")
    end
end

p `git branch`
p `git show-branch`

`git log --pretty=%H`.split("\n").each do |hash|
    other = `git branch --contains #{hash} | grep -v "danger_base\|danger_head\|#{merging}"`
    unless other.empty?()
        p other
        break
    end
end
