message("Working!")

base = github.branch_for_base
merging = github.branch_for_head

message("This pr merge #{merging} into #{base}")

if base == "main" || base == "master"
    unless merging.start_with?("hotfix/") || merging.start_with?("release/")
        fail("You can't merge this branch into main/master")
    end
end
