name: "Danger Ruby"
on: [pull_request]

jobs:
  build:
    name: Danger Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install
        run: |
          gem install 'danger'
      - name: Danger
        run: danger --fail-on-errors=true --dangerfile=.github/Dangerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
