name: "Danger JS"
on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: yarn add danger
      - name: Danger
        run: yarn danger ci --fail-on-errors=true
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DANGER_DISABLE_TRANSPILATION: true
