name: Container Action
on: workflow_dispatch

jobs:
  tbls:
    runs-on: ubuntu-latest
    steps:
      - name: version
        uses: docker://ghcr.io/k1low/tbls:latest
        with:
            args: version
      - name: help
        uses: docker://ghcr.io/k1low/tbls:latest
        with:
            args: doc --help
