name: Container Action
on: workflow_dispatch

jobs:
  tbls:
    runs-on: ubuntu-latest
    steps:
      - name: version
        uses: docker://ghcr.io/k1low/tbls:latest
        with:
          args: version
      - name: help
        uses: docker://ghcr.io/k1low/tbls:latest
        with:
          args: doc --help
      - name: Ubuntu version
        uses: docker://ubuntu:latest
        with:
          args: cat /etc/os-release
      - name: Python version
        uses: docker://python:latest
        with:
          args: python --version
      - name: Python OS info
        uses: docker://python:latest
        with:
          args: /bin/cat /etc/os-release
